.pragma library

var defaultSource = "https://forum.sailfishos.org/"
var defaultTitle  = "SFOS Forum"

var list = [
    { url: "https://forum.arduino.cc/",             title: "Arduino"},
    { url: "https://discuss.codecademy.com/",       title: "Code academy"},
    { url: "https://discourse.cmake.org/",          title: "CMake"},
    { url: "https://forums.docker.com/",            title: "Docker"},
    { url: "https://meta.discourse.org/",           title: "Discourse"},
    { url: "https://community.e.foundation/",       title: "/e/ Foundation"},
    { url: "https://discuss.emberjs.com/",          title: "Ember.js"},
    { url: "https://forum.fairphone.com/",          title: "Fairphone"},
    { url: "https://forum.f-droid.org/",            title: "FDroid"},
    { url: "https://discussion.fedoraproject.org/", title: "Fedora"},
    { url: "https://community.frame.work/",         title: "Framework"},
    { url: "https://forum.garudalinux.org/",        title: "Garuda Linux"},
    { url: "https://discuss.atom.io/",              title: "Github Atom"},
    { url: "https://discourse.gnome.org/",          title: "Gnome"},
    { url: "https://discuss.haiku-os.org/",         title: "Haiku"},
    { url: "https://discourse.haskell.org/",        title: "Haskell"},
    { url: "https://community.home-assistant.io/",  title: "Home Assistant"},
    { url: "https://discuss.huggingface.co/",       title: "Huggingface"},
    { url: "https://we.incognito.org/",             title: "Incognito"},
    { url: "https://forum.jami.net/",               title: "Jami"},
    { url: "https://discuss.kakoune.com/",          title: "Kakoune"},
    { url: "https://discuss.kde.org/",              title: "KDE"},
    { url: "https://community.libretranslate.com/", title: "Libretranslate"},
    { url: "https://discuss.linuxcontainers.org/",  title: "LXC"},
    { url: "https://forum.manjaro.org/",            title: "Manjaro"},
    { url: "https://mixxx.discourse.group/",        title: "MIXXX"},
    { url: "https://community.monzo.com/",          title: "Monzo"},
    { url: "https://discourse.mozilla.org/",        title: "Mozilla"},
    { url: "https://help.nextcloud.com/",           title: "Nextcloud"},
    { url: "https://discourse.nixos.org/",          title: "Nixos"},
    { url: "https://forum.nomadbsd.org/",           title: "NomadBSD"},
    { url: "https://forums.developer.nvidia.com/",  title: "Nvidia"},
    { url: "https://discuss.ocaml.org/",            title: "OCaml"},
    { url: "https://community.octoprint.org/",      title: "Octoprint"},
    { url: "https://community.openai.com/",         title: "OpenAI"},
    { url: "https://forum.opennmt.net/",            title: "OpenNMT"},
    { url: "https://community.openstreetmap.org/",  title: "OpenStreetMap"},
    { url: "https://forum.openwrt.org/",            title: "OpenWrt"},
    { url: "https://discourse.paraview.org/",       title: "ParaView"},
    { url: "https://discuss.pixls.us/",             title: "PIXLS.US"},
    { url: "https://discourse.pi-hole.net/",        title: "Pi-hole"},
    { url: "https://forums.puri.sm/",               title: "PureOS"},
    { url: "https://forum.rclone.org/",             title: "rclone"},
    { url: "https://forum.bestpractical.com/",      title: "Request Tracker (IR)"},
    { url: "https://community.revolut.com/",        title: "Revolut"},
    { url: "https://discourse.ros.org/",            title: "ROS"},
    { url: "https://users.rust-lang.org/",          title: "Rust"},
    { url: "https://discourse.differentk.fyi/",     title: "SpecialK"},
    { url: "https://forum.syncthing.net/",          title: "Syncthing"},
    { url: "https://discuss.tindie.com/",           title: "Tindie"},
    { url: "https://forum.torproject.org/",         title: "Tor Project"},
    { url: "https://community.transifex.com/",      title: "Transifex"},
    { url: "https://discourse.ubuntu.com/",         title: "Ubuntu"},
    { url: "https://discourse.vtk.org/",            title: "VTK"},
    { url: "https://forums.whonix.org/",            title: "Whonix"},
    { url: "https://winraid.level1techs.com/",      title: "Win-Raid"},
    { url: "https://discuss.zerotier.com/",         title: "ZeroTierOne"},
    { url: defaultSource,                           title: defaultTitle},
]
